name: Blank Workflow

# Aciona o workflow quando uma pull request for aberta, sincronizada ou reaberta
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Exibir mensagem de sucesso
        run: echo "Workflow acionado via Pull Request!"
 
