name: Manual Workflow with Self-Hosted Runner

# Disparador manual
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Exibir mensagem de sucesso
        run: echo "Executando no self-hosted runner!"
