name: Manual Workflow

# Disparador manual
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Exibir mensagem de sucesso
        run: echo "Workflow executado com sucesso!"
